export const REQUEST_CARS_BIKES="REQUEST_CARS_BIKES";
export const GET_SUCCESS_CARS_BIKES="GET_SUCCESS_CARS_BIKES";
export const FAILURE_CARS_BIKES="FAILURE_CARS_BIKES";
export const STORE_SEARCH_VALUE="STORE_SEARCH_VALUE";